services:

  mysql:
    image: mysql:8.0
    container_name: shortly_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ukardeparth48
      MYSQL_DATABASE: urlshortener
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shortly_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: shortly_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ukardeparth48
      DB_NAME: urlshortener
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BASE_URL: http://localhost:8000
    depends_on:
      mysql:
        condition: service_healthy
      redis: 
        condition: service_started
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: shortly_frontend
    ports:
      - "3000:80"

volumes:
  mysql_data:
  redis_data: